const cons = require('./constant');

module.exports.getBuffData = function(eff) {
  var retObj = {};
  
  var buffCode = undefined;
  if (eff.multiple) {
    var rand = Math.floor(Math.random() * eff.buffCode.length);
    buffCode = eff.buffCode[rand];
  } else {
    buffCode = eff.buffCode;
  }
  
  retObj.id = buffCode;
  retObj.isDebuff = true;
  retObj.dispellable = true;
  retObj.effect = [];
  retObj.durOff = cons.DURATION_TYPE_TURN_START;
  var effectObj = {};
  
  switch (buffCode) {
  case 1 : 
    retObj.name = '화상';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 1;
    effectObj.isPercentMax = true;
    effectObj.value = 0.05;
    effectObj.type = cons.DAMAGE_TYPE_ABSOLUTE;
    retObj.effect.push(effectObj);
    break;
  case 2 : 
    retObj.name = '중독';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 1;
    effectObj.isPercentCur = true;
    effectObj.value = 0.08;
    effectObj.type = cons.DAMAGE_TYPE_ABSOLUTE;
    retObj.effect.push(effectObj);
    break;
  case 3 : 
    retObj.name = '출혈';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10003;
    effectObj.isPercentMax = true;
    effectObj.value = 0.05;
    effectObj.buff = retObj;
    effectObj.type = cons.DAMAGE_TYPE_ABSOLUTE;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 1;
    effectObj.isPercentMax = true;
    effectObj.value = 0.03;
    effectObj.type = cons.DAMAGE_TYPE_ABSOLUTE;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 17;
    effectObj.value = 0.15;
    effectObj.buff = retObj;
    effectObj.buffTarget = [201726];
    retObj.effect.push(effectObj);
    break;
  case 4 : 
    retObj.name = '기절';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10004;
    retObj.effect.push(effectObj);
    break;
  case 5 : 
    retObj.name = '수면';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10005;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 6 : 
    retObj.name = '탈진';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10006;
    effectObj.type = cons.DAMAGE_TYPE_PHYSICAL;
    retObj.effect.push(effectObj);
    break;
  case 7 : 
    retObj.name = '침묵';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10006;
    effectObj.type = cons.DAMAGE_TYPE_MAGICAL;
    retObj.effect.push(effectObj);
    break;
  case 8 : 
    retObj.name = '실명';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10;
    effectObj.key = 'hit';
    effectObj.value = 0.5;
    retObj.effect.push(effectObj);
    break;
  case 9 : 
    retObj.name = '마비';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    effectObj = {};
    effectObj.code = 10;
    effectObj.key = 'evasion';
    effectObj.value = 0.5;
    retObj.effect.push(effectObj);
    break;
  case 10 : 
    retObj.name = '봉인';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10010;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 11 : 
    retObj.name = '혼란';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10011;
    retObj.effect.push(effectObj);
    break;
  case 10001 : 
    retObj.name = '깨진 유리검';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -15;
    effectObj.key = 'phyAtk';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -15;
    effectObj.key = 'magAtk';
    retObj.effect.push(effectObj);
    break;
  case 10002 : 
    retObj.name = '허수아비의 원념';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.02;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.02;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 10003 : 
    retObj.name = '가치 하락';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.maxStack = 50;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 19;
    effectObj.value = 0.01;
    effectObj.key = 'phyAtk';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 19;
    effectObj.value = 0.01;
    effectObj.key = 'magAtk';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 10004 : 
    retObj.name = '샤에 물듦';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.durOff = null;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 18;
    effectObj.isPercent = true;
    effectObj.value = 0.1;
    effectObj.type = cons.DAMAGE_TYPE_ABSOLUTE;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 10005 : 
    retObj.name = '핏빛 관통';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.durOff = cons.DURATION_TYPE_TURN_END;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 1;
    effectObj.key = 'pierce';
    retObj.effect.push(effectObj);
    break;
  case 10006 : 
    retObj.name = '불길의 아이우스타';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.durOff = cons.DURATION_TYPE_TURN_END;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 7;
    effectObj.type = cons.DAMAGE_TYPE_MAGICAL_FIXED;
    effectObj.damage = 16;
    effectObj.calc = true;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 20;
    effectObj.buffCode = 1;
    effectObj.dur = 1;
    effectObj.chance = 1.03;
    effectObj.active = cons.ACTIVE_TYPE_ATTACK;
    retObj.effect.push(effectObj);
    break;
  case 10007 : 
    retObj.name = '검은 정원의 가지';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 20101 : 
    retObj.name = '혼돈의 힘';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 2;
    effectObj.value = eff.value;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 20102 : 
    retObj.name = '파괴됨';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 1;
    effectObj.value = eff.value;
    effectObj.type = cons.DAMAGE_TYPE_MAGICAL;
    retObj.effect.push(effectObj);
    break;
  case 20103 : 
    retObj.name = '지옥불길';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 3;
    effectObj = {};
    effectObj.code = 1;
    effectObj.value = eff.value;
    effectObj.type = cons.DAMAGE_TYPE_MAGICAL;
    retObj.effect.push(effectObj);
    break;
  case 20091 : 
    retObj.name = '서리 폭풍우';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.isDebuff = false;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = eff.value;
    effectObj.key = 'hpRegen';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 20092 : 
    retObj.name = '사자의 군대';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.stack = 8;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 4;
    effectObj.value = eff.value;
    effectObj.type = cons.DAMAGE_TYPE_PHYSICAL;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 5;
    effectObj.value = eff.value;
    retObj.effect.push(effectObj);
    break;
  case 20093 : 
    retObj.name = '서리한 포식';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = eff.value;
    effectObj.key = 'spRegen';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 20171 : 
    retObj.name = '이검 취약';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.15;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.15;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 20172 : 
    retObj.name = '이검 취약';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.1;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.1;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 20173 : 
    retObj.name = '흐름 관찰';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    retObj.durOff = null;
    effectObj = {};
    effectObj.code = 6;
    effectObj.value = eff.value;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 20174 : 
    retObj.name = '대환수 영랑';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 7;
    effectObj.turnReduce = 1;
    effectObj.buff = retObj;
    effectObj.key = 'phyAtk';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 8;
    effectObj.value = 0.2;
    retObj.effect.push(effectObj);
    break;
  case 20175 : 
    retObj.name = '진실을 가로막는 허상';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    retObj.durOff = cons.DURATION_TYPE_TURN_END;
    effectObj = {};
    effectObj.code = 9;
    retObj.effect.push(effectObj);
    break;
  case 20176 : 
    retObj.name = '스파크스터';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 9;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'hpRegen';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'spRegen';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'spCharge';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 1.5;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 1.5;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 11;
    effectObj.buffCode = 201706;
    effectObj.dur = 2;
    retObj.effect.push(effectObj);
    break;
  case 201706 : 
    retObj.name = '기절';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 10004;
    retObj.effect.push(effectObj);
    break;
  case 20177 : 
    retObj.name = '불확실성';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.02;
    effectObj.key = 'evasion';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 12;
    effectObj.value = 3;
    effectObj.key = 'curSp';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 20178 : 
    retObj.name = '프사이-정신교란';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.12;
    effectObj.key = 'hit';
    retObj.effect.push(effectObj);
    break;
  case 20179 : 
    retObj.name = '프사이-정신분열';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 10011;
    retObj.effect.push(effectObj);
    break;
  case 201710 : 
    retObj.name = '프사이-피해의식';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 10010;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201711 : 
    retObj.name = '프사이-의식불명';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 10005;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201712 : 
    retObj.name = '프사이-의식붕괴';
    retObj.nameType = cons.NAME_KOR_NO_aEND_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 1;
    effectObj.value = eff.value;
    effectObj.type = cons.DAMAGE_TYPE_PHYSICAL;
    retObj.effect.push(effectObj);
    break;
  case 201713 : 
    retObj.name = '혼돈의 완성';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0;
    effectObj.key = 'hpRegen';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0;
    effectObj.key = 'phyAtk';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0;
    effectObj.key = 'magAtk';
    retObj.effect.push(effectObj);
    break;
  case 201714 : 
    retObj.name = '중단점_';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.durOff = null;
    retObj.isDebuff = false;
    break;
  case 201715 : 
    retObj.name = '시간 왜곡';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.stackType = 4;
    effectObj = {};
    effectObj.code = 13;
    effectObj.chance = 1;
    effectObj.turnReduce = 1;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201716 : 
    retObj.name = '에너지 코어';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.stack = 3;
    retObj.durOff = null;
    retObj.isDebuff = false;
    break;
  case 201717 : 
    retObj.name = '복합 장갑';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 3;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 1;
    effectObj.key = 'spRegen';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.15;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.15;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 201718 : 
    retObj.name = '방벽 시스템';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 14;
    effectObj.buffCode = 201719;
    effectObj.dur = null;
    effectObj.value = 0.1;
    effectObj.isPercent = true;
    effectObj.key = 'maxHp';
    effectObj.active = cons.ACTIVE_TYPE_TURN_END;
    retObj.effect.push(effectObj);
    break;
  case 201719 : 
    retObj.name = '요새 방벽';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    retObj.durOff = null;
    effectObj = {};
    effectObj.code = 6;
    effectObj.value = eff.value;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201720 : 
    retObj.name = '출력 모드';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    retObj.durOff = null;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.15;
    effectObj.key = 'crit';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 15;
    effectObj.buff = retObj;
    effectObj.removeOnCrit = true;
    retObj.effect.push(effectObj);
    break;
  case 201721 : 
    retObj.name = '재구축 중..';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.5;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.5;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 10;
    effectObj.value = 0;
    effectObj.key = 'spRegen';
    retObj.effect.push(effectObj);
    break;
  case 201722 : 
    retObj.name = '프로토콜 충전';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 16;
    retObj.effect.push(effectObj);
    break;
  case 201723 : 
    retObj.name = '방출 감전';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.25;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    break;
  case 201724 : 
    retObj.name = '방전';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    effectObj = {};
    effectObj.code = 10004;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 11;
    effectObj.buffCode = 201725;
    effectObj.dur = null;
    retObj.effect.push(effectObj);
    break;
  case 201725 : 
    retObj.name = '전하 충전';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.maxStack = 5;
    retObj.isDebuff = false;
    retObj.durOff = null;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.02;
    effectObj.key = 'phyReduce';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.02;
    effectObj.key = 'magReduce';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201726 : 
    retObj.name = '환영';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 3;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.02;
    effectObj.key = 'crit';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.06;
    effectObj.key = 'evasion';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 12;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201727 : 
    retObj.name = '조여오는 어둠';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.05;
    effectObj.key = 'hit';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201728 : 
    retObj.name = '암흑';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.1;
    effectObj.key = 'crit';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 15;
    effectObj.buff = retObj;
    effectObj.onAnyCrit = true;
    effectObj.stealSp = 3;
    retObj.effect.push(effectObj);
    break;
  case 201729 : 
    retObj.name = '키보드 샷건';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 2;
    effectObj.value = eff.value;
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201730 : 
    retObj.name = '해탈';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 1;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 9;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 5;
    effectObj.key = 'spRegen';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.15;
    effectObj.key = 'phyReduce';
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 0.15;
    effectObj.key = 'magReduce';
    retObj.effect.push(effectObj);
    break;
  case 201731 : 
    retObj.name = '거북이';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.maxStack = 5;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = eff.value;
    effectObj.key = 'phyReduce';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201732 : 
    retObj.name = '꼬장부리기';
    retObj.nameType = cons.NAME_KOR_NO_END_CONS;
    retObj.stackType = 1;
    retObj.durOff = null;
    retObj.isDebuff = false;
    effectObj = {};
    effectObj.code = 7;
    effectObj.turnReduce = 1;
    effectObj.buff = retObj;
    effectObj.additional = 0.15;
    retObj.effect.push(effectObj);
    break;
  case 201733 : 
    retObj.name = '팩트폭격';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.maxStack = 5;
    retObj.durOff = null;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = eff.value;
    effectObj.key = 'phyReduce';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = eff.value;
    effectObj.key = 'magReduce';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201734 : 
    retObj.name = '한심한 시선';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -0.1;
    effectObj.key = 'critDmg';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -1;
    effectObj.key = 'spRegen';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -1;
    effectObj.key = 'spCharge';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201735 : 
    retObj.name = '화병';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.stackType = 2;
    retObj.stack = 1;
    retObj.durOff = null;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -3;
    effectObj.key = 'hpRegen';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -1;
    effectObj.key = 'spRegen';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = -1;
    effectObj.key = 'spCharge';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  case 201736 : 
    retObj.name = '한심함';
    retObj.nameType = cons.NAME_KOR_END_CONS;
    retObj.isDebuff = false;
    retObj.effect = [];
    effectObj = {};
    effectObj.code = 3;
    effectObj.value = 1;
    effectObj.key = 'evasion';
    effectObj.buff = retObj;
    retObj.effect.push(effectObj);
    break;
  }

  return retObj;
}