var NAME_KOR_NO_END_CONS = 0;
var NAME_KOR_END_CONS = 1;

var ITEM_TYPE_WEAPON = 0;
var ITEM_TYPE_ARMOR = 1;
var ITEM_TYPE_TRINKET = 2;

var DAMAGE_TYPE_ABSOLUTE = 0;
var DAMAGE_TYPE_PHYSICAL = 1;
var DAMAGE_TYPE_MAGICAL = 2;

var SKILL_TYPE_DRIVE = 10;
var SKILL_TYPE_SPECIAL = 100;

var ACTIVE_TYPE_ATTACK = 0;

var EFFECT_TYPE_SELF_BUFF = 1;
var EFFECT_TYPE_OPP_BUFF = 2;
var EFFECT_TYPE_SELF_SP = 3;
var EFFECT_TYPE_SELF_HP = 4;
var EFFECT_TYPE_ADD_HIT = 5;

var DURATION_TYPE_TURN_START = 1;
var DURATION_TYPE_TURN_END = 0;

  var charLeft = {};
  var charRight = {};
  _initChar(charLeft);
  _initChar(charRight);

  charLeft.name = '카이네스 엠더츠';
  charLeft.nameType = NAME_KOR_NO_END_CONS;
  charLeft.items = {};
  var itemObj = {};
  itemObj.name = '엠더타이드 인장 지팡이';
  itemObj.nameType = NAME_KOR_NO_END_CONS;
  itemObj.type = ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.magAtk = 12;
  itemObj.stat.spCharge = 4;
  itemObj.effect = [];
  charLeft.items.weapon = itemObj;
  itemObj = {};
  itemObj.name = '엠더타이드 세공 상의';
  itemObj.nameType = NAME_KOR_NO_END_CONS;
  itemObj.type = ITEM_TYPE_ARMOR;
  itemObj.stat = {};
  itemObj.stat.maxHp = 100;
  itemObj.stat.spRegen = 3;
  itemObj.effect = [];
  charLeft.items.armor = itemObj;
  itemObj = {};
  itemObj.name = '기만의 인장';
  itemObj.nameType = NAME_KOR_END_CONS;
  itemObj.type = ITEM_TYPE_TRINKET;
  itemObj.stat = {};
  itemObj.stat.magAtk = 2;
  itemObj.stat.spCharge = 2;
  itemObj.stat.spRegen = 2;
  itemObj.effect = [];
  charLeft.items.trinket = itemObj;

  charLeft.skill = {};
  charLeft.skill.base = [];

  var skillObj = {};
  skillObj.code = 20101;
  skillObj.name = '혼돈의 화살';
  skillObj.nameType = NAME_KOR_END_CONS;
  skillObj.type = DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1.2;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20101;
  effectObj.buffDur = 2;
  effectObj.value = 15;
  skillObj.effect.push(effectObj);           
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20102;
  skillObj.name = '파괴의 저주';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.7;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 0.5;
  effectObj.buffCode = 20102;
  effectObj.buffDur = 3;
  effectObj.value = 0.1;
  skillObj.effect.push(effectObj);            
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20103;
  skillObj.name = '망각의 계약';
  skillObj.nameType = NAME_KOR_END_CONS;
  skillObj.type = DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1.1;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_SP;
  effectObj.chance = 0.3;
  effectObj.value = 15;
  skillObj.effect.push(effectObj); 
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20104;
  skillObj.name = '생명력 전환';
  skillObj.nameType = NAME_KOR_END_CONS;
  skillObj.type = SKILL_TYPE_DRIVE;
  skillObj.active = ACTIVE_TYPE_ATTACK;
  skillObj.cost = 0;
  skillObj.chance = 0.5;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_SP;
  effectObj.chance = 1;
  effectObj.value = 25;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_HP;
  effectObj.chance = 1;
  effectObj.value = -20;
  skillObj.effect.push(effectObj); 
  charLeft.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 20105;
  skillObj.name = '지옥불길';
  skillObj.nameType = NAME_KOR_END_CONS;
  skillObj.type = SKILL_TYPE_SPECIAL;
  skillObj.cost = 90;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20103;
  effectObj.buffDur = 5;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj);    
  effectObj = {};
  effectObj.code = EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20103;
  effectObj.buffDur = 5;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj);    
  charLeft.skill.special = skillObj;

  charRight.name = '아서스 메네실';
  charRight.nameType = NAME_KOR_END_CONS;
  charRight.skill = {};
  charRight.skill.base = [];
  charRight.items = {};
  itemObj = {};
  itemObj.name = '서리한';
  itemObj.nameType = NAME_KOR_END_CONS;
  itemObj.type = ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 12;
  itemObj.stat.spRegen = 4;
  itemObj.effect = [];
  charRight.items.weapon = itemObj;
  itemObj = {};
  itemObj.name = '리치 왕의 세공 갑옷';
  itemObj.nameType = NAME_KOR_NO_END_CONS;
  itemObj.type = ITEM_TYPE_ARMOR;
  itemObj.stat = {};
  itemObj.stat.maxHp = 120;
  itemObj.stat.magReduce = 0.1;
  itemObj.effect = [];
  charRight.items.armor = itemObj;
  itemObj = {};
  itemObj.name = '서리 끼인 영혼의 망토';
  itemObj.nameType = NAME_KOR_NO_END_CONS;
  itemObj.type = ITEM_TYPE_TRINKET;
  itemObj.stat = {};
  itemObj.stat.crit = 0.25;
  itemObj.effect = [];
  charRight.items.trinket = itemObj;

  var skillObj = {};
  skillObj.code = 20091;
  skillObj.name = '죽음의 고리';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.3;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_HP;
  effectObj.chance = 1;
  effectObj.value = 15;
  skillObj.effect.push(effectObj);           
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20092;
  skillObj.name = '울부짖는 한파';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 0.5;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 4;
  effectObj.buffDur = 1;
  skillObj.effect.push(effectObj);            
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20093;
  skillObj.name = '서리 폭풍우';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.2;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20091;
  effectObj.buffDur = 3;
  effectObj.value = 4;
  skillObj.effect.push(effectObj); 
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20094;
  skillObj.name = '서리한이 굶주렸다';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = SKILL_TYPE_DRIVE;
  skillObj.active = ACTIVE_TYPE_ATTACK;
  skillObj.cost = 5;
  skillObj.chance = 0.25;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = EFFECT_TYPE_ADD_HIT;
  effectObj.chance = 1;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20093;
  effectObj.buffDur = null;
  effectObj.value = 1;
  skillObj.effect.push(effectObj); 
  charRight.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 20095;
  skillObj.name = '사자의 군대';
  skillObj.nameType = NAME_KOR_NO_END_CONS;
  skillObj.type = SKILL_TYPE_SPECIAL;
  skillObj.cost = 120;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20092;
  effectObj.buffDur = 8;
  effectObj.value = 0.02;
  skillObj.effect.push(effectObj); 
  charRight.skill.special = skillObj;
  
  function _initChar(char) {
    char.stat = {};
    char.stat.maxHp = 400;
    char.stat.spCharge = 5;
    char.stat.hpRegen = 0;
    char.stat.spRegen = 5;
    char.stat.phyAtk = 20;
    char.stat.magAtk = 20;
    char.stat.crit = 0.05;
    char.stat.critDmg = 1.5;
    char.stat.phyReduce = 0;
    char.stat.magReduce = 0;
    char.stat.hit = 1;
    char.stat.evasion = 0;
    char.base = JSON.parse(JSON.stringify(char.stat));
    char.inventory = [];
    char.items = {};
  }
  //setCharacter('thelichking', '1', JSON.stringify(charRight));
  
  module.exports.kines = charLeft;
  module.exports.lk = charRight;