const cons = require('./constant');

  var charLeft = {};
  _initChar(charLeft);

  charLeft.name = '카이네스 엠더츠';
  charLeft.nameType = cons.NAME_KOR_NO_END_CONS;
  charLeft.title = '고대 흑마법사';
  
  charLeft.items = {};
  var itemObj = {};
  itemObj.name = '엠더타이드 인장 지팡이';
  itemObj.nameType = cons.NAME_KOR_NO_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.rank = 9;
  itemObj.rarity = cons.ITEM_RARITY_RARE;
  itemObj.stat = {};
  itemObj.stat.magAtk = 12;
  itemObj.stat.spCharge = 4;
  itemObj.effect = [];
  charLeft.items.weapon = itemObj;
  itemObj = {};
  itemObj.name = '엠더타이드 세공 상의';
  itemObj.nameType = cons.NAME_KOR_NO_END_CONS;
  itemObj.type = cons.ITEM_TYPE_ARMOR;
  itemObj.rank = 9;
  itemObj.rarity = cons.ITEM_RARITY_UNIQUE;
  itemObj.stat = {};
  itemObj.stat.maxHp = 100;
  itemObj.stat.spRegen = 3;
  itemObj.effect = [];
  charLeft.items.armor = itemObj;
  itemObj = {};
  itemObj.name = '기만의 인장';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_TRINKET;
  itemObj.rank = 9;
  itemObj.rarity = cons.ITEM_RARITY_UNCOMMON;
  itemObj.stat = {};
  itemObj.stat.magAtk = 2;
  itemObj.stat.spCharge = 2;
  itemObj.stat.spRegen = 2;
  itemObj.effect = [];
  charLeft.items.trinket = itemObj;

  charLeft.skill = {};
  charLeft.skill.base = [];

  var skillObj = {};
  skillObj.code = 20101;
  skillObj.name = '혼돈의 화살';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1.2;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20101;
  effectObj.buffDur = 2;
  effectObj.value = 15;
  skillObj.effect.push(effectObj);           
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20102;
  skillObj.name = '파괴의 저주';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.7;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 0.5;
  effectObj.buffCode = 20102;
  effectObj.buffDur = 3;
  effectObj.value = 0.1;
  skillObj.effect.push(effectObj);            
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20103;
  skillObj.name = '망각의 계약';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1.1;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_SP;
  effectObj.chance = 0.3;
  effectObj.value = 15;
  skillObj.effect.push(effectObj); 
  charLeft.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20104;
  skillObj.name = '생명력 전환';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_ATTACK;
  skillObj.cost = 0;
  skillObj.chance = 0.5;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_SP;
  effectObj.chance = 1;
  effectObj.value = 25;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_HP;
  effectObj.chance = 1;
  effectObj.value = -20;
  skillObj.effect.push(effectObj); 
  charLeft.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 20105;
  skillObj.name = '지옥불길';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 90;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20103;
  effectObj.buffDur = 5;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj);    
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20103;
  effectObj.buffDur = 5;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj);    
  charLeft.skill.special = skillObj;


  var charRight = {};
  _initChar(charRight);
  
  charRight.name = '아서스 메네실';
  charRight.nameType = cons.NAME_KOR_END_CONS;
  charRight.title = '리치 왕';
  charRight.rank = 9;
  charRight.level = 1;
  charRight.exp = 0;
  charRight.reqExp = 100;
  
  charRight.skill = {};
  charRight.skill.base = [];
  charRight.items = {};
  itemObj = {};
  itemObj.name = '서리한';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.rank = 9;
  itemObj.rarity = cons.ITEM_RARITY_RARE;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 12;
  itemObj.stat.spRegen = 4;
  itemObj.effect = [];
  charRight.items.weapon = itemObj;
  itemObj = {};
  itemObj.name = '리치 왕의 세공 갑옷';
  itemObj.nameType = cons.NAME_KOR_NO_END_CONS;
  itemObj.type = cons.ITEM_TYPE_ARMOR;
  itemObj.rank = 8;
  itemObj.rarity = cons.ITEM_RARITY_COMMON;
  itemObj.stat = {};
  itemObj.stat.maxHp = 120;
  itemObj.stat.magReduce = 0.1;
  itemObj.effect = [];
  charRight.items.armor = itemObj;
  itemObj = {};
  itemObj.name = '서리 끼인 영혼의 망토';
  itemObj.nameType = cons.NAME_KOR_NO_END_CONS;
  itemObj.type = cons.ITEM_TYPE_SUBARMOR;
  itemObj.rank = 9;
  itemObj.rarity = cons.ITEM_RARITY_EPIC;
  itemObj.stat = {};
  itemObj.stat.crit = 0.25;
  itemObj.effect = [];
  charRight.items.subarmor = itemObj;

  var skillObj = {};
  skillObj.code = 20091;
  skillObj.name = '죽음의 고리';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.3;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_HP;
  effectObj.chance = 1;
  effectObj.value = 15;
  skillObj.effect.push(effectObj);           
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20092;
  skillObj.name = '울부짖는 한파';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 0.5;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 4;
  effectObj.buffDur = 1;
  skillObj.effect.push(effectObj);            
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20093;
  skillObj.name = '서리 폭풍우';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.2;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20091;
  effectObj.buffDur = 3;
  effectObj.value = 4;
  skillObj.effect.push(effectObj); 
  charRight.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20094;
  skillObj.name = '서리한이 굶주렸다';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_ATTACK;
  skillObj.cost = 5;
  skillObj.chance = 0.25;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_ADD_HIT;
  effectObj.chance = 1;
  effectObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  effectObj.value = 0.4;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20093;
  effectObj.buffDur = null;
  effectObj.value = 1;
  skillObj.effect.push(effectObj); 
  charRight.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 20095;
  skillObj.name = '사자의 군대';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 120;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20092;
  effectObj.buffDur = 8;
  effectObj.value = 0.02;
  skillObj.effect.push(effectObj); 
  charRight.skill.special = skillObj;


  var charSeriers = {};
  _initChar(charSeriers);
  
  charSeriers.name = '세리어스 플로에르시아';
  charSeriers.nameType = cons.NAME_KOR_NO_END_CONS;
  charSeriers.title = '플로에르시아 가주 임시 대행';
  charSeriers.rank = 9;
  charSeriers.level = 1;
  charSeriers.exp = 0;
  charSeriers.reqExp = 100;
  
  charSeriers.skill = {};
  charSeriers.skill.base = [];
  charSeriers.items = {};
  itemObj = {};
  itemObj.name = '테스터의 검 9';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 11;
  itemObj.stat.magAtk = 11;
  itemObj.stat.maxHp = 64;
  itemObj.stat.phyReduce = 0.01;
  itemObj.stat.magReduce = 0.01;
  itemObj.stat.spRegen = 1;
  itemObj.stat.hpRegen = 1;
  itemObj.stat.crit = 0.01;
  itemObj.effect = [];
  charSeriers.items.weapon = itemObj;

  var skillObj = {};
  skillObj.code = 20171;
  skillObj.name = '이검 영원';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.3;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20171;
  effectObj.buffDur = 1;
  skillObj.effect.push(effectObj);           
  effectObj = {};
  effectObj.onCrit = true;
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20172;
  effectObj.buffDur = 1;
  skillObj.effect.push(effectObj);           
  charSeriers.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20172;
  skillObj.name = '흐름 관찰';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SHIELD_FROM_DAMAGE;
  effectObj.chance = 1;
  effectObj.buffCode = 20173;
  effectObj.buffDur = null;
  effectObj.value = 0.8;
  skillObj.effect.push(effectObj);            
  charSeriers.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20173;
  skillObj.name = '환수 강령';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.7;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20174;
  effectObj.buffDur = 4;
  effectObj.value = 0.2;
  skillObj.effect.push(effectObj); 
  charSeriers.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20174;
  skillObj.name = '진실을 가로막는 허상';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_TAKE_HIT;
  skillObj.cost = 10;
  skillObj.chance = 0.05;
  skillObj.cooldown = 4;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_CANCEL_DAMAGE;
  effectObj.chance = 1;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20175;
  effectObj.buffDur = 1;
  skillObj.effect.push(effectObj); 
  charSeriers.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 20175;
  skillObj.name = '광차원 스파크스터';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 165;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20176;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 4;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 7;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 8;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  charSeriers.skill.special = skillObj;


  var charPsi = {};
  _initChar(charPsi);
  
  charPsi.name = '프사이';
  charPsi.nameType = cons.NAME_KOR_NO_END_CONS;
  charPsi.title = '혼돈의 군체';
  charPsi.rank = 9;
  charPsi.level = 1;
  charPsi.exp = 0;
  charPsi.reqExp = 100;
  
  charPsi.skill = {};
  charPsi.skill.base = [];
  charPsi.items = {};
  itemObj = {};
  itemObj.name = '테스터의 검 9';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 11;
  itemObj.stat.magAtk = 11;
  itemObj.stat.maxHp = 64;
  itemObj.stat.phyReduce = 0.01;
  itemObj.stat.magReduce = 0.01;
  itemObj.stat.spRegen = 1;
  itemObj.stat.hpRegen = 1;
  itemObj.stat.crit = 0.01;
  itemObj.effect = [];
  charPsi.items.weapon = itemObj;

  var skillObj = {};
  skillObj.code = 20176;
  skillObj.name = '정신 교란';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 1.1;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkNot = [20177];
  skillObj.effect.push(effectObj);           
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 0.35;
  effectObj.buffCode = 20178;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj);           
  charPsi.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20177;
  skillObj.name = '의식의 지평선';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.7;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 0.35;
  effectObj.multiple = true;
  effectObj.buffCode = [20179, 201710, 201711];
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj);            
  charPsi.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20178;
  skillObj.name = '붕괴';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.2;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_CONVERT_BUFF;
  effectObj.chance = 0.35;
  effectObj.buffTarget = [20178, 20179, 201710, 201711];
  effectObj.buffCode = 201712;
  effectObj.buffDur = 3;
  effectObj.value = 0.25;
  skillObj.effect.push(effectObj); 
  charPsi.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 20179;
  skillObj.name = '불확실성';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_TURN_END;
  skillObj.cost = 3;
  skillObj.chance = 1;
  skillObj.cooldown = 0;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  skillObj.effect.push(effectObj); 
  charPsi.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 201710;
  skillObj.name = '대통합';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 130;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201713;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTarget = [20178, 20179, 201710, 201711, 201712];
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkOpp = [20178];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkOpp = [20179];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkOpp =[201710];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkOpp = [201711];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 20177;
  effectObj.buffDur = null;
  effectObj.chkOpp = [201712];
  skillObj.effect.push(effectObj); 
  charPsi.skill.special = skillObj;


  var charJulius = {};
  _initChar(charJulius);
  
  charJulius.name = '줄리어스 엠더츠';
  charJulius.nameType = cons.NAME_KOR_NO_END_CONS;
  charJulius.title = '타임 코더';
  charJulius.rank = 9;
  charJulius.level = 1;
  charJulius.exp = 0;
  charJulius.reqExp = 100;
  
  charJulius.skill = {};
  charJulius.skill.base = [];
  charJulius.items = {};
  itemObj = {};
  itemObj.name = '테스터의 검 9';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 11;
  itemObj.stat.magAtk = 11;
  itemObj.stat.maxHp = 64;
  itemObj.stat.phyReduce = 0.01;
  itemObj.stat.magReduce = 0.01;
  itemObj.stat.spRegen = 1;
  itemObj.stat.hpRegen = 1;
  itemObj.stat.crit = 0.01;
  itemObj.effect = [];
  charJulius.items.weapon = itemObj;

  var skillObj = {};
  skillObj.code = 201711;
  skillObj.name = '중단점 설정';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.7;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_RETURN;
  effectObj.chance = 1;
  effectObj.buffCode = 201714;
  effectObj.chk = [201714];
  skillObj.effect.push(effectObj);           
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201714;
  effectObj.buffDur = null;
  skillObj.effect.push(effectObj);           
  charJulius.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201712;
  skillObj.name = '다중 선택 트리';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.9;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SKILL_RESELECT;
  effectObj.chance = 0.2;
  skillObj.effect.push(effectObj);            
  charJulius.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201713;
  skillObj.name = '시간 조작';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.4;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_ADD_HIT;
  effectObj.chance = 0.15;
  effectObj.type = cons.DAMAGE_TYPE_MAGICAL;
  effectObj.value = 0.5;
  skillObj.effect.push(effectObj); 
  charJulius.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201714;
  skillObj.name = '디버그 모드';
  skillObj.nameType = cons.NAME_KOR_NO_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_TAKE_HIT;
  skillObj.cost = 30;
  skillObj.chance = 0.1;
  skillObj.cooldown = 0;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_SP;
  effectObj.chance = 1;
  effectObj.value = 30;
  effectObj.chkNot = [201714];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_RETURN;
  effectObj.chance = 1;
  effectObj.debug = true;
  effectObj.chk = [201714];
  skillObj.effect.push(effectObj); 
  charJulius.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 201715;
  skillObj.name = '시간 왜곡';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 75;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201715;
  effectObj.buffDur = null;
  skillObj.effect.push(effectObj); 
  charJulius.skill.special = skillObj;


  var charAeika = {};
  _initChar(charAeika);
  
  charAeika.name = '에이카';
  charAeika.nameType = cons.NAME_KOR_NO_END_CONS;
  charAeika.title = '움직이는 요새';
  charAeika.rank = 9;
  charAeika.level = 1;
  charAeika.exp = 0;
  charAeika.reqExp = 100;
  
  charAeika.skill = {};
  charAeika.skill.base = [];
  charAeika.items = {};
  itemObj = {};
  itemObj.name = '테스터의 검 9';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 11;
  itemObj.stat.magAtk = 11;
  itemObj.stat.maxHp = 64;
  itemObj.stat.phyReduce = 0.01;
  itemObj.stat.magReduce = 0.01;
  itemObj.stat.spRegen = 1;
  itemObj.stat.hpRegen = 1;
  itemObj.stat.crit = 0.01;
  itemObj.effect = [];
  charAeika.items.weapon = itemObj;

  var skillObj = {};
  skillObj.code = 201716;
  skillObj.name = '모듈 - 복합 장갑';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 0.5;
  skillObj.effect = [];
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201717;
  effectObj.buffDur = 3;
  effectObj.chk = [201716];
  skillObj.effect.push(effectObj);       
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTarget = [201716];
  effectObj.stack = -1;
  effectObj.chk = [201716];
  skillObj.effect.push(effectObj);    
  charAeika.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201717;
  skillObj.name = '모듈 - 방벽 시스템 작동';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.5;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201718;
  effectObj.buffDur = 2;
  effectObj.chk = [201716];
  skillObj.effect.push(effectObj);       
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTarget = [201716];
  effectObj.stack = -1;
  effectObj.chk = [201716];
  skillObj.effect.push(effectObj);    
  charAeika.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201718;
  skillObj.name = '모듈 - 출력 엔진';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 2.0;
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201720;
  effectObj.buffDur = null;
  effectObj.chk = [201716];
  effectObj.critNot = true;
  skillObj.effect.push(effectObj);       
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELECTION;
  effectObj.chance = 1;
  effectObj.selectChances = [0.2, 1];
  effectObj.options = [];
  var optObj = {};
  optObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  optObj.buffCode = 4;
  optObj.buffDur = 1;
  optObj.chance = 1;
  effectObj.options.push(optObj);
  optObj = {};
  optObj.code = cons.EFFECT_TYPE_SELF_SP;
  optObj.value = 10;
  optObj.chance = 1;
  effectObj.options.push(optObj);
  effectObj.chk = [201716];
  effectObj.onCrit = true;
  skillObj.effect.push(effectObj);
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTarget = [201716];
  effectObj.stack = -1;
  effectObj.chk = [201716];
  skillObj.effect.push(effectObj);
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTargetCode = 10010;
  effectObj.stack = -1;
  effectObj.chkNot = [201716];
  skillObj.effect.push(effectObj);    
  charAeika.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201719;
  skillObj.name = '비상 프로토콜 - 재구축';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_TURN_END;
  skillObj.cost = 0;
  skillObj.chance = 1;
  skillObj.cooldown = 0;
  skillObj.chkNot = [201716];
  skillObj.effect = [];
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201724;
  effectObj.buffDur = 1;
  effectObj.chkTurn = 2;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201716;
  effectObj.buffDur = null;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201721;
  effectObj.buffDur = 3;
  effectObj.chkHp = 0.2;
  effectObj.chkNot = [201722];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201722;
  effectObj.buffDur = 20;
  effectObj.chkHp = 0.2;
  effectObj.chkNot = [201722];
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF_REFRESH;
  effectObj.chance = 1;
  effectObj.buffTarget = [201725];
  effectObj.stack = -5;
  effectObj.chkHp = 0.2;
  effectObj.chkNot = [201722];
  skillObj.effect.push(effectObj);    
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_HP;
  effectObj.chance = 1;
  effectObj.isPercentMax = true;
  effectObj.value = 0.3;
  effectObj.chkHp = 0.2;
  effectObj.chkNot = [201722];
  skillObj.effect.push(effectObj); 
  charAeika.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 201720;
  skillObj.name = '제압 프로토콜 - 에너지 방출';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 150;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELECTION;
  effectObj.chance = 1;
  effectObj.selectChances = [0.5, 1];
  effectObj.options = [];
  var optObj = {};
  optObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  optObj.buffCode = 4;
  optObj.buffDur = 3;
  optObj.chance = 1;
  effectObj.options.push(optObj);
  optObj = {};
  optObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  optObj.buffCode = 201723;
  optObj.buffDur = 3;
  optObj.chance = 1;
  effectObj.options.push(optObj);
  skillObj.effect.push(effectObj);
  charAeika.skill.special = skillObj;


  var charAeohelm = {};
  _initChar(charAeohelm);
  
  charAeohelm.name = '에오헬름';
  charAeohelm.nameType = cons.NAME_KOR_END_CONS;
  charAeohelm.title = '밤의 추격자';
  charAeohelm.rank = 9;
  charAeohelm.level = 1;
  charAeohelm.exp = 0;
  charAeohelm.reqExp = 100;
  
  charAeohelm.skill = {};
  charAeohelm.skill.base = [];
  charAeohelm.items = {};
  itemObj = {};
  itemObj.name = '테스터의 검 9';
  itemObj.nameType = cons.NAME_KOR_END_CONS;
  itemObj.type = cons.ITEM_TYPE_WEAPON;
  itemObj.stat = {};
  itemObj.stat.phyAtk = 11;
  itemObj.stat.magAtk = 11;
  itemObj.stat.maxHp = 64;
  itemObj.stat.phyReduce = 0.01;
  itemObj.stat.magReduce = 0.01;
  itemObj.stat.spRegen = 1;
  itemObj.stat.hpRegen = 1;
  itemObj.stat.crit = 0.01;
  itemObj.effect = [];
  charAeohelm.items.weapon = itemObj;

  var skillObj = {};
  skillObj.code = 201721;
  skillObj.name = '사악한 암습';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 0.9;
  skillObj.effect = [];  
  var effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 0.25;
  effectObj.chanceAddKey = 'crit';
  effectObj.buffCode = 3;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  charAeohelm.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201722;
  skillObj.name = '조여오는 어둠';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_MAGICAL;
  skillObj.damage = 0.9;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_SP;
  effectObj.chance = 1;
  effectObj.buffTarget =[201726];
  effectObj.value = 3;
  effectObj.chk = [201726];
  skillObj.effect.push(effectObj);
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_OPP_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201727;
  effectObj.buffDur = 2;
  effectObj.buffTarget =[201726];
  effectObj.chk = [201726];
  skillObj.effect.push(effectObj); 
  charAeohelm.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201723;
  skillObj.name = '그림자 습격';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  skillObj.damage = 1.0;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_RESOLVE_DRIVE;
  effectObj.chance = 1;
  effectObj.chkNot = [201726];
  skillObj.effect.push(effectObj);      
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_ADD_HIT;
  effectObj.chance = 1;
  effectObj.buffTarget = [201726];
  effectObj.type = cons.DAMAGE_TYPE_MAGICAL;
  effectObj.value = 0.2;
  effectObj.chk = [201726];
  skillObj.effect.push(effectObj);  
  charAeohelm.skill.base.push(skillObj);

  skillObj = {};
  skillObj.code = 201724;
  skillObj.name = '환영';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_DRIVE;
  skillObj.active = cons.ACTIVE_TYPE_TURN_START;
  skillObj.cost = 5;
  skillObj.chance = 0.25;
  skillObj.cooldown = 0;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201726;
  effectObj.buffDur = 5;
  skillObj.effect.push(effectObj); 
  charAeohelm.skill.drive = skillObj;

  skillObj = {};
  skillObj.code = 201725;
  skillObj.name = '환영 습격';
  skillObj.nameType = cons.NAME_KOR_END_CONS;
  skillObj.type = cons.SKILL_TYPE_SPECIAL;
  skillObj.cost = 125;
  skillObj.effect = [];  
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201726;
  effectObj.buffDur = 5;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201726;
  effectObj.buffDur = 5;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_SELF_BUFF;
  effectObj.chance = 1;
  effectObj.buffCode = 201728;
  effectObj.buffDur = 3;
  skillObj.effect.push(effectObj); 
  effectObj = {};
  effectObj.code = cons.EFFECT_TYPE_ADD_HIT;
  effectObj.chance = 1;
  effectObj.buffTarget = [201726];
  effectObj.separate = true;
  effectObj.type = cons.DAMAGE_TYPE_PHYSICAL;
  effectObj.value = 0.6;
  skillObj.effect.push(effectObj);  
  charAeohelm.skill.special = skillObj;
  
  function _initChar(char) {
    char.stat = {};
    char.stat.maxHp = 200;
    char.stat.spCharge = 5;
    char.stat.hpRegen = 0;
    char.stat.spRegen = 5;
    char.stat.phyAtk = 20;
    char.stat.magAtk = 20;
    char.stat.crit = 0.05;
    char.stat.critDmg = 1.5;
    char.stat.phyReduce = 0;
    char.stat.magReduce = 0;
    char.stat.hit = 1;
    char.stat.evasion = 0;
    char.base = JSON.parse(JSON.stringify(char.stat));
    char.inventory = [];
    char.items = {};
    char.rank = 9;
    char.level = 1;
    char.exp = 0;
    char.reqExp = 100;
    char.statPoint = 0;
    char.actionPoint = 0;
  }
  
  module.exports.kines = charLeft;
  module.exports.lk = charRight;
  module.exports.seriers = charSeriers; 
  module.exports.psi = charPsi; 
  module.exports.julius = charJulius; 
  module.exports.aeika = charAeika; 
  module.exports.aeohelm = charAeohelm; 