module.exports = {
    NAME_KOR_NO_END_CONS : 0,
    NAME_KOR_END_CONS : 1,

    ITEM_TYPE_WEAPON : 0,
    ITEM_TYPE_ARMOR : 1,
    ITEM_TYPE_SUBARMOR : 2,
    ITEM_TYPE_TRINKET : 3,

    DAMAGE_TYPE_ABSOLUTE : 0,
    DAMAGE_TYPE_PHYSICAL : 1,
    DAMAGE_TYPE_MAGICAL : 2,

    SKILL_TYPE_DRIVE : 10,
    SKILL_TYPE_SPECIAL : 100,

    ACTIVE_TYPE_ATTACK : 0,
    ACTIVE_TYPE_TAKE_HIT : 1,
    ACTIVE_TYPE_TURN_END : 2,

    EFFECT_TYPE_SELF_BUFF : 1,
    EFFECT_TYPE_OPP_BUFF : 2,
    EFFECT_TYPE_SELF_SP : 3,
    EFFECT_TYPE_SELF_HP : 4,
    EFFECT_TYPE_ADD_HIT : 5,
    EFFECT_TYPE_SHIELD_FROM_DAMAGE : 6,
    EFFECT_TYPE_SELF_CONVERT_BUFF : 7,
    EFFECT_TYPE_OPP_CONVERT_BUFF : 8,
    EFFECT_TYPE_SELF_BUFF_REFRESH : 9,
    EFFECT_TYPE_OPP_BUFF_REFRESH : 10,
    EFFECT_TYPE_RETURN : 11,
    EFFECT_TYPE_SKILL_RESELECT : 12,

    DURATION_TYPE_TURN_START : 1,
    DURATION_TYPE_TURN_END : 0
}