const cons = require('./constant');

var itemList = [];
module.exports.list = itemList;
itemList[0] = { id : 0, name : '﻿초보자의 단련검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 9, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 8, phyAtkMax : 12, magAtkMin : 8, magAtkMax : 12, crit : 0.02 }, effect : [] };
itemList[1] = { id : 1, name : '낡은 장검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 13, phyAtkMax : 17, magAtkMin : 13, magAtkMax : 17, crit : 0.02 }, effect : [] };
itemList[2] = { id : 2, name : '비파형 청동검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 20, phyAtkMax : 24, magAtkMin : 20, magAtkMax : 24, crit : 0.03 }, effect : [] };
itemList[3] = { id : 3, name : '토룡의 뿔칼', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 27, phyAtkMax : 33, magAtkMin : 27, magAtkMax : 33, crit : 0.03 }, effect : [] };
itemList[4] = { id : 4, name : '고수의 단련검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 35, phyAtkMax : 41, magAtkMin : 35, magAtkMax : 41, crit : 0.04 }, effect : [] };
itemList[5] = { id : 5, name : '상아검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 43, phyAtkMax : 51, magAtkMin : 43, magAtkMax : 51, crit : 0.04 }, effect : [] };
itemList[6] = { id : 6, name : '역날의 태도', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 54, phyAtkMax : 62, magAtkMin : 54, magAtkMax : 62, crit : 0.05 }, effect : [] };
itemList[7] = { id : 7, name : '프로토 윙 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 65, phyAtkMax : 75, magAtkMin : 65, magAtkMax : 75, crit : 0.06 }, effect : [] };
itemList[8] = { id : 8, name : '미완성 하르콘 검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 77, phyAtkMax : 89, magAtkMin : 77, magAtkMax : 89, crit : 0.07 }, effect : [] };
itemList[9] = { id : 9, name : '롱 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 9, phyAtkMax : 13, magAtkMin : 9, magAtkMax : 13, crit : 0.02 }, effect : [] };
itemList[10] = { id : 10, name : '브로드 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 15, phyAtkMax : 19, magAtkMin : 15, magAtkMax : 19, crit : 0.02 }, effect : [] };
itemList[11] = { id : 11, name : '기사의 철검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 22, phyAtkMax : 26, magAtkMin : 22, magAtkMax : 26, crit : 0.03 }, effect : [] };
itemList[12] = { id : 12, name : '공격대의 검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 30, phyAtkMax : 36, magAtkMin : 30, magAtkMax : 36, crit : 0.03 }, effect : [] };
itemList[13] = { id : 13, name : '루벨라이트 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 39, phyAtkMax : 45, magAtkMin : 39, magAtkMax : 45, crit : 0.04 }, effect : [] };
itemList[14] = { id : 14, name : '아벤드라이트 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 48, phyAtkMax : 56, magAtkMin : 48, magAtkMax : 56, crit : 0.04 }, effect : [] };
itemList[15] = { id : 15, name : '쌍날의 태도', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 60, phyAtkMax : 68, magAtkMin : 60, magAtkMax : 68, crit : 0.05 }, effect : [] };
itemList[16] = { id : 16, name : '윙 소드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 72, phyAtkMax : 82, magAtkMin : 72, magAtkMax : 82, crit : 0.06 }, effect : [] };
itemList[17] = { id : 17, name : '하르콘 검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 85, phyAtkMax : 97, magAtkMin : 85, magAtkMax : 97, crit : 0.07 }, effect : [] };
itemList[18] = { id : 18, name : '단궁', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 10, phyAtkMax : 20, magAtkMin : 10, magAtkMax : 20, crit : 0.02 }, effect : [] };
itemList[19] = { id : 19, name : '조잡한 석궁', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 17, phyAtkMax : 27, magAtkMin : 17, magAtkMax : 27, crit : 0.03 }, effect : [] };
itemList[20] = { id : 20, name : '전직 용사의 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 23, phyAtkMax : 38, magAtkMin : 23, magAtkMax : 38, crit : 0.03 }, effect : [] };
itemList[21] = { id : 21, name : '본메이드 보우', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 31, phyAtkMax : 46, magAtkMin : 31, magAtkMax : 46, crit : 0.04 }, effect : [] };
itemList[22] = { id : 22, name : '매사냥 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 37, phyAtkMax : 57, magAtkMin : 37, magAtkMax : 57, crit : 0.04 }, effect : [] };
itemList[23] = { id : 23, name : '함정설치용 석궁', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 48, phyAtkMax : 68, magAtkMin : 48, magAtkMax : 68, crit : 0.05 }, effect : [] };
itemList[24] = { id : 24, name : '가시뼈 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 58, phyAtkMax : 83, magAtkMin : 58, magAtkMax : 83, crit : 0.06 }, effect : [] };
itemList[25] = { id : 25, name : '미완성 하르콘 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 68, phyAtkMax : 98, magAtkMin : 68, magAtkMax : 98, crit : 0.07 }, effect : [] };
itemList[26] = { id : 26, name : '장궁', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 12, phyAtkMax : 22, magAtkMin : 12, magAtkMax : 22, crit : 0.02 }, effect : [] };
itemList[27] = { id : 27, name : '가죽 덧댄 장궁', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 19, phyAtkMax : 29, magAtkMin : 19, magAtkMax : 29, crit : 0.03 }, effect : [] };
itemList[28] = { id : 28, name : '공격대의 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 26, phyAtkMax : 41, magAtkMin : 26, magAtkMax : 41, crit : 0.03 }, effect : [] };
itemList[29] = { id : 29, name : '컴포지트 보우', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 34, phyAtkMax : 49, magAtkMin : 34, magAtkMax : 49, crit : 0.04 }, effect : [] };
itemList[30] = { id : 30, name : '전쟁활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 42, phyAtkMax : 62, magAtkMin : 42, magAtkMax : 62, crit : 0.04 }, effect : [] };
itemList[31] = { id : 31, name : '센티넬 보우', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 54, phyAtkMax : 74, magAtkMin : 54, magAtkMax : 74, crit : 0.05 }, effect : [] };
itemList[32] = { id : 32, name : '윙 보우', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 65, phyAtkMax : 90, magAtkMin : 65, magAtkMax : 90, crit : 0.06 }, effect : [] };
itemList[33] = { id : 33, name : '하르콘 활', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 76, phyAtkMax : 106, magAtkMin : 76, magAtkMax : 106, crit : 0.07 }, effect : [] };
itemList[34] = { id : 34, name : '단창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 17, phyAtkMax : 21, magAtkMin : 9, magAtkMax : 13, crit : 0.02 }, effect : [] };
itemList[35] = { id : 35, name : '대나무창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 26, phyAtkMax : 30, magAtkMin : 15, magAtkMax : 19, crit : 0.03 }, effect : [] };
itemList[36] = { id : 36, name : '화극', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 35, phyAtkMax : 41, magAtkMin : 20, magAtkMax : 26, crit : 0.03 }, effect : [] };
itemList[37] = { id : 37, name : '미늘창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 45, phyAtkMax : 51, magAtkMin : 26, magAtkMax : 32, crit : 0.04 }, effect : [] };
itemList[38] = { id : 38, name : '다변형 폴암', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 55, phyAtkMax : 63, magAtkMin : 31, magAtkMax : 39, crit : 0.04 }, effect : [] };
itemList[39] = { id : 39, name : '가름창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 69, phyAtkMax : 77, magAtkMin : 40, magAtkMax : 48, crit : 0.05 }, effect : [] };
itemList[40] = { id : 40, name : '글레이브', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 83, phyAtkMax : 93, magAtkMin : 48, magAtkMax : 58, crit : 0.06 }, effect : [] };
itemList[41] = { id : 41, name : '미완성 하르콘 창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 98, phyAtkMax : 110, magAtkMin : 56, magAtkMax : 68, crit : 0.07 }, effect : [] };
itemList[42] = { id : 42, name : '장창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 19, phyAtkMax : 23, magAtkMin : 10, magAtkMax : 14, crit : 0.02 }, effect : [] };
itemList[43] = { id : 43, name : '언월도', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 28, phyAtkMax : 32, magAtkMin : 16, magAtkMax : 20, crit : 0.03 }, effect : [] };
itemList[44] = { id : 44, name : '그레이트랜스', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 38, phyAtkMax : 44, magAtkMin : 22, magAtkMax : 28, crit : 0.03 }, effect : [] };
itemList[45] = { id : 45, name : '파이크', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 49, phyAtkMax : 55, magAtkMin : 28, magAtkMax : 34, crit : 0.04 }, effect : [] };
itemList[46] = { id : 46, name : '월광나비의 뿔', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 61, phyAtkMax : 69, magAtkMin : 35, magAtkMax : 43, crit : 0.04 }, effect : [] };
itemList[47] = { id : 47, name : '파르티잔', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 76, phyAtkMax : 84, magAtkMin : 44, magAtkMax : 52, crit : 0.05 }, effect : [] };
itemList[48] = { id : 48, name : '로스릭 기사의 장창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 91, phyAtkMax : 101, magAtkMin : 53, magAtkMax : 63, crit : 0.06 }, effect : [] };
itemList[49] = { id : 49, name : '하르콘 창', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 108, phyAtkMax : 120, magAtkMin : 62, magAtkMax : 74, crit : 0.07 }, effect : [] };
itemList[50] = { id : 50, name : '땔감용 손도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 15, phyAtkMax : 23, magAtkMin : 7, magAtkMax : 15, crit : 0.02 }, effect : [] };
itemList[51] = { id : 51, name : '대부', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 24, phyAtkMax : 32, magAtkMin : 13, magAtkMax : 21, crit : 0.03 }, effect : [] };
itemList[52] = { id : 52, name : '이글거리는 전쟁도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 32, phyAtkMax : 44, magAtkMin : 17, magAtkMax : 29, crit : 0.03 }, effect : [] };
itemList[53] = { id : 53, name : '벼려낸 가로날도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 42, phyAtkMax : 54, magAtkMin : 23, magAtkMax : 35, crit : 0.04 }, effect : [] };
itemList[54] = { id : 54, name : '달 모양 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 51, phyAtkMax : 67, magAtkMin : 27, magAtkMax : 43, crit : 0.04 }, effect : [] };
itemList[55] = { id : 55, name : '룬새김 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 65, phyAtkMax : 81, magAtkMin : 36, magAtkMax : 52, crit : 0.05 }, effect : [] };
itemList[56] = { id : 56, name : '대장장이의 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 78, phyAtkMax : 98, magAtkMin : 43, magAtkMax : 63, crit : 0.06 }, effect : [] };
itemList[57] = { id : 57, name : '미완성 하르콘 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 92, phyAtkMax : 116, magAtkMin : 50, magAtkMax : 74, crit : 0.07 }, effect : [] };
itemList[58] = { id : 58, name : '전투 손도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 17, phyAtkMax : 25, magAtkMin : 8, magAtkMax : 16, crit : 0.02 }, effect : [] };
itemList[59] = { id : 59, name : '전투 양날 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 26, phyAtkMax : 34, magAtkMin : 14, magAtkMax : 22, crit : 0.03 }, effect : [] };
itemList[60] = { id : 60, name : '처형자의 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 35, phyAtkMax : 47, magAtkMin : 19, magAtkMax : 31, crit : 0.03 }, effect : [] };
itemList[61] = { id : 61, name : '거대한 양날 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 46, phyAtkMax : 58, magAtkMin : 25, magAtkMax : 37, crit : 0.04 }, effect : [] };
itemList[62] = { id : 62, name : '흑기사의 대형 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 57, phyAtkMax : 73, magAtkMin : 31, magAtkMax : 47, crit : 0.04 }, effect : [] };
itemList[63] = { id : 63, name : '분쇄자의 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 72, phyAtkMax : 88, magAtkMin : 40, magAtkMax : 56, crit : 0.05 }, effect : [] };
itemList[64] = { id : 64, name : '용을 가르는 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 86, phyAtkMax : 106, magAtkMin : 48, magAtkMax : 68, crit : 0.06 }, effect : [] };
itemList[65] = { id : 65, name : '하르콘 도끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 102, phyAtkMax : 126, magAtkMin : 56, magAtkMax : 80, crit : 0.07 }, effect : [] };
itemList[66] = { id : 66, name : '교편', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 9, phyAtkMax : 13, magAtkMin : 17, magAtkMax : 21, crit : 0.02 }, effect : [] };
itemList[67] = { id : 67, name : '민무늬 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 15, phyAtkMax : 19, magAtkMin : 26, magAtkMax : 30, crit : 0.03 }, effect : [] };
itemList[68] = { id : 68, name : '그루의 마법막대', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 20, phyAtkMax : 26, magAtkMin : 35, magAtkMax : 41, crit : 0.03 }, effect : [] };
itemList[69] = { id : 69, name : '전투마법사의 홀', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 26, phyAtkMax : 32, magAtkMin : 45, magAtkMax : 51, crit : 0.04 }, effect : [] };
itemList[70] = { id : 70, name : '룬 새김 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 31, phyAtkMax : 39, magAtkMin : 55, magAtkMax : 63, crit : 0.04 }, effect : [] };
itemList[71] = { id : 71, name : '얼음노래꾼의 망치', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 40, phyAtkMax : 48, magAtkMin : 69, magAtkMax : 77, crit : 0.05 }, effect : [] };
itemList[72] = { id : 72, name : '흐릿한 자수정 홀', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 48, phyAtkMax : 58, magAtkMin : 83, magAtkMax : 93, crit : 0.06 }, effect : [] };
itemList[73] = { id : 73, name : '미완성 하르콘 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 56, phyAtkMax : 68, magAtkMin : 98, magAtkMax : 110, crit : 0.07 }, effect : [] };
itemList[74] = { id : 74, name : '블랙우드 로드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 10, phyAtkMax : 14, magAtkMin : 19, magAtkMax : 23, crit : 0.02 }, effect : [] };
itemList[75] = { id : 75, name : '초승달의 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 16, phyAtkMax : 20, magAtkMin : 28, magAtkMax : 32, crit : 0.03 }, effect : [] };
itemList[76] = { id : 76, name : '석영 수정 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 22, phyAtkMax : 28, magAtkMin : 38, magAtkMax : 44, crit : 0.03 }, effect : [] };
itemList[77] = { id : 77, name : '빛이 깃든 망치', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 28, phyAtkMax : 34, magAtkMin : 49, magAtkMax : 55, crit : 0.04 }, effect : [] };
itemList[78] = { id : 78, name : '제왕의 홀', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 35, phyAtkMax : 43, magAtkMin : 61, magAtkMax : 69, crit : 0.04 }, effect : [] };
itemList[79] = { id : 79, name : '결정화된 용의 미부', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 44, phyAtkMax : 52, magAtkMin : 76, magAtkMax : 84, crit : 0.05 }, effect : [] };
itemList[80] = { id : 80, name : '자수정 홀', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 53, phyAtkMax : 63, magAtkMin : 91, magAtkMax : 101, crit : 0.06 }, effect : [] };
itemList[81] = { id : 81, name : '하르콘 마법봉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 62, phyAtkMax : 74, magAtkMin : 108, magAtkMax : 120, crit : 0.07 }, effect : [] };
itemList[82] = { id : 82, name : '딱총나무 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 7, phyAtkMax : 15, magAtkMin : 15, magAtkMax : 23, crit : 0.02 }, effect : [] };
itemList[83] = { id : 83, name : '마녀의 오래된 빗자루', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 13, phyAtkMax : 21, magAtkMin : 24, magAtkMax : 32, crit : 0.03 }, effect : [] };
itemList[84] = { id : 84, name : '요목의 가지', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 17, phyAtkMax : 29, magAtkMin : 32, magAtkMax : 44, crit : 0.03 }, effect : [] };
itemList[85] = { id : 85, name : '이야기꾼의 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 23, phyAtkMax : 35, magAtkMin : 42, magAtkMax : 54, crit : 0.04 }, effect : [] };
itemList[86] = { id : 86, name : '오래된 위저드 셉터', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 27, phyAtkMax : 43, magAtkMin : 51, magAtkMax : 67, crit : 0.04 }, effect : [] };
itemList[87] = { id : 87, name : '마술사의 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 36, phyAtkMax : 52, magAtkMin : 65, magAtkMax : 81, crit : 0.05 }, effect : [] };
itemList[88] = { id : 88, name : '탁한 오팔 스태프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 43, phyAtkMax : 63, magAtkMin : 78, magAtkMax : 98, crit : 0.06 }, effect : [] };
itemList[89] = { id : 89, name : '미완성 하르콘 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 50, phyAtkMax : 74, magAtkMin : 92, magAtkMax : 116, crit : 0.07 }, effect : [] };
itemList[90] = { id : 90, name : '플라워신트 스태프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 8, phyAtkMax : 16, magAtkMin : 17, magAtkMax : 25, crit : 0.02 }, effect : [] };
itemList[91] = { id : 91, name : '현인의 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 14, phyAtkMax : 22, magAtkMin : 26, magAtkMax : 34, crit : 0.03 }, effect : [] };
itemList[92] = { id : 92, name : '요술지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 19, phyAtkMax : 31, magAtkMin : 35, magAtkMax : 47, crit : 0.03 }, effect : [] };
itemList[93] = { id : 93, name : '마도사의 빗자루', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 25, phyAtkMax : 37, magAtkMin : 46, magAtkMax : 58, crit : 0.04 }, effect : [] };
itemList[94] = { id : 94, name : '스펠워드 스태프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 31, phyAtkMax : 47, magAtkMin : 57, magAtkMax : 73, crit : 0.04 }, effect : [] };
itemList[95] = { id : 95, name : '궁정마술사의 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 40, phyAtkMax : 56, magAtkMin : 72, magAtkMax : 88, crit : 0.05 }, effect : [] };
itemList[96] = { id : 96, name : '영롱한 오팔 스태프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 48, phyAtkMax : 68, magAtkMin : 86, magAtkMax : 106, crit : 0.06 }, effect : [] };
itemList[97] = { id : 97, name : '하르콘 지팡이', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 56, phyAtkMax : 80, magAtkMin : 102, magAtkMax : 126, crit : 0.07 }, effect : [] };
itemList[98] = { id : 98, name : '쓰로잉 나이프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 9, phyAtkMax : 13, magAtkMin : 9, magAtkMax : 13, crit : 0.04 }, effect : [] };
itemList[99] = { id : 99, name : '맥가이버 만능칼', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 15, phyAtkMax : 19, magAtkMin : 15, magAtkMax : 19, crit : 0.06 }, effect : [] };
itemList[100] = { id : 100, name : '도적 단도', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 20, phyAtkMax : 26, magAtkMin : 20, magAtkMax : 26, crit : 0.06 }, effect : [] };
itemList[101] = { id : 101, name : '의식용 단도', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 26, phyAtkMax : 32, magAtkMin : 26, magAtkMax : 32, crit : 0.08 }, effect : [] };
itemList[102] = { id : 102, name : '하르페', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 31, phyAtkMax : 39, magAtkMin : 31, magAtkMax : 39, crit : 0.08 }, effect : [] };
itemList[103] = { id : 103, name : '패링 대거', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 40, phyAtkMax : 48, magAtkMin : 40, magAtkMax : 48, crit : 0.1 }, effect : [] };
itemList[104] = { id : 104, name : '엽병단의 비검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 48, phyAtkMax : 58, magAtkMin : 48, magAtkMax : 58, crit : 0.12 }, effect : [] };
itemList[105] = { id : 105, name : '미완성 하르콘 단검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { phyAtkMin : 56, phyAtkMax : 68, magAtkMin : 56, magAtkMax : 68, crit : 0.14 }, effect : [] };
itemList[106] = { id : 106, name : '은 단검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 10, phyAtkMax : 14, magAtkMin : 10, magAtkMax : 14, crit : 0.04 }, effect : [] };
itemList[107] = { id : 107, name : '컴뱃 나이프', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 16, phyAtkMax : 20, magAtkMin : 16, magAtkMax : 20, crit : 0.06 }, effect : [] };
itemList[108] = { id : 108, name : '꼬리뼈 단검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 22, phyAtkMax : 28, magAtkMin : 22, magAtkMax : 28, crit : 0.06 }, effect : [] };
itemList[109] = { id : 109, name : '니들 스팅', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 28, phyAtkMax : 34, magAtkMin : 28, magAtkMax : 34, crit : 0.08 }, effect : [] };
itemList[110] = { id : 110, name : '샤픈 스틸레토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 35, phyAtkMax : 43, magAtkMin : 35, magAtkMax : 43, crit : 0.08 }, effect : [] };
itemList[111] = { id : 111, name : '그라디우스', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 44, phyAtkMax : 52, magAtkMin : 44, magAtkMax : 52, crit : 0.1 }, effect : [] };
itemList[112] = { id : 112, name : '남옥의 단검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 53, phyAtkMax : 63, magAtkMin : 53, magAtkMax : 63, crit : 0.12 }, effect : [] };
itemList[113] = { id : 113, name : '하르콘 단검', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { phyAtkMin : 62, phyAtkMax : 74, magAtkMin : 62, magAtkMax : 74, crit : 0.14 }, effect : [] };
itemList[114] = { id : 114, name : '평상복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 9, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 28, evasion : 0.05, spRegen : 1, phyReduce : 0.01, magReduce : 0.01 }, effect : [] };
itemList[115] = { id : 115, name : '판초우의', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 56, evasion : 0.05, spRegen : 1, phyReduce : 0.02, magReduce : 0.02 }, effect : [] };
itemList[116] = { id : 116, name : '예식용 정장', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 105, evasion : 0.05, spRegen : 1, phyReduce : 0.03, magReduce : 0.03 }, effect : [] };
itemList[117] = { id : 117, name : '고풍스러운 드레스', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 154, evasion : 0.05, spRegen : 1, phyReduce : 0.05, magReduce : 0.05 }, effect : [] };
itemList[118] = { id : 118, name : '용병의 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 217, evasion : 0.05, spRegen : 1, phyReduce : 0.07, magReduce : 0.07 }, effect : [] };
itemList[119] = { id : 119, name : '성녀의 의복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 294, evasion : 0.05, spRegen : 1, phyReduce : 0.09, magReduce : 0.09 }, effect : [] };
itemList[120] = { id : 120, name : '늠름한 불한당의 조끼', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 385, evasion : 0.05, spRegen : 1, phyReduce : 0.11, magReduce : 0.11 }, effect : [] };
itemList[121] = { id : 121, name : '마력이 깃든 예복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 490, evasion : 0.05, spRegen : 1, phyReduce : 0.13, magReduce : 0.13 }, effect : [] };
itemList[122] = { id : 122, name : '비전의 가죽 튜닉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 609, evasion : 0.05, spRegen : 1, phyReduce : 0.16, magReduce : 0.16 }, effect : [] };
itemList[123] = { id : 123, name : '덧댄 가죽옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 31, evasion : 0.05, spRegen : 1, phyReduce : 0.011, magReduce : 0.011 }, effect : [] };
itemList[124] = { id : 124, name : '신형 방탄복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 62, evasion : 0.05, spRegen : 1, phyReduce : 0.022, magReduce : 0.022 }, effect : [] };
itemList[125] = { id : 125, name : '마법사 교복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 116, evasion : 0.05, spRegen : 1, phyReduce : 0.033, magReduce : 0.033 }, effect : [] };
itemList[126] = { id : 126, name : '3K단의 로브', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 169, evasion : 0.05, spRegen : 1, phyReduce : 0.055, magReduce : 0.055 }, effect : [] };
itemList[127] = { id : 127, name : '하얀 가운', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 239, evasion : 0.05, spRegen : 1, phyReduce : 0.077, magReduce : 0.077 }, effect : [] };
itemList[128] = { id : 128, name : '축복받은 방상외피', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 323, evasion : 0.05, spRegen : 1, phyReduce : 0.099, magReduce : 0.099 }, effect : [] };
itemList[129] = { id : 129, name : '오리엔탈 실키안 로브', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 424, evasion : 0.05, spRegen : 1, phyReduce : 0.121, magReduce : 0.121 }, effect : [] };
itemList[130] = { id : 130, name : '대사냥꾼의 스웨이드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 539, evasion : 0.05, spRegen : 1, phyReduce : 0.143, magReduce : 0.143 }, effect : [] };
itemList[131] = { id : 131, name : '고룡의 가죽 튜닉', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 670, evasion : 0.05, spRegen : 1, phyReduce : 0.176, magReduce : 0.176 }, effect : [] };
itemList[132] = { id : 132, name : '어니언 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 9, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 40, critDmg : 0.1, phyReduce : 0.01, magReduce : 0.01 }, effect : [] };
itemList[133] = { id : 133, name : '기름 먹인 가죽 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 80, critDmg : 0.1, phyReduce : 0.02, magReduce : 0.02 }, effect : [] };
itemList[134] = { id : 134, name : '동물뼈 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 150, critDmg : 0.1, phyReduce : 0.03, magReduce : 0.03 }, effect : [] };
itemList[135] = { id : 135, name : '낡은 방검복', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 220, critDmg : 0.1, phyReduce : 0.05, magReduce : 0.05 }, effect : [] };
itemList[136] = { id : 136, name : '거대거북 등딱지', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 310, critDmg : 0.1, phyReduce : 0.07, magReduce : 0.07 }, effect : [] };
itemList[137] = { id : 137, name : '종자의 편자 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 420, critDmg : 0.1, phyReduce : 0.09, magReduce : 0.09 }, effect : [] };
itemList[138] = { id : 138, name : '불사대의 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 550, critDmg : 0.1, phyReduce : 0.11, magReduce : 0.11 }, effect : [] };
itemList[139] = { id : 139, name : '드레이크 스케일 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 700, critDmg : 0.1, phyReduce : 0.13, magReduce : 0.13 }, effect : [] };
itemList[140] = { id : 140, name : '미완성 하르콘 메일', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 870, critDmg : 0.1, phyReduce : 0.16, magReduce : 0.16 }, effect : [] };
itemList[141] = { id : 141, name : '스테디드 레더 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 44, critDmg : 0.1, phyReduce : 0.011, magReduce : 0.011 }, effect : [] };
itemList[142] = { id : 142, name : '경기병대 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 88, critDmg : 0.1, phyReduce : 0.022, magReduce : 0.022 }, effect : [] };
itemList[143] = { id : 143, name : '블랙본 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 165, critDmg : 0.1, phyReduce : 0.033, magReduce : 0.033 }, effect : [] };
itemList[144] = { id : 144, name : '브리건딘', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 242, critDmg : 0.1, phyReduce : 0.055, magReduce : 0.055 }, effect : [] };
itemList[145] = { id : 145, name : '미늘 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 341, critDmg : 0.1, phyReduce : 0.077, magReduce : 0.077 }, effect : [] };
itemList[146] = { id : 146, name : '체인 메일', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 462, critDmg : 0.1, phyReduce : 0.099, magReduce : 0.099 }, effect : [] };
itemList[147] = { id : 147, name : '오더메이드 체인 메일', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 605, critDmg : 0.1, phyReduce : 0.121, magReduce : 0.121 }, effect : [] };
itemList[148] = { id : 148, name : '용비늘 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 770, critDmg : 0.1, phyReduce : 0.143, magReduce : 0.143 }, effect : [] };
itemList[149] = { id : 149, name : '하르콘 체인 메일', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 957, critDmg : 0.1, phyReduce : 0.176, magReduce : 0.176 }, effect : [] };
itemList[150] = { id : 150, name : '무쇠 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 104, evasion : -0.05, phyReduce : 0.02, magReduce : 0.02 }, effect : [] };
itemList[151] = { id : 151, name : '패잔병의 군장', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 195, evasion : -0.05, phyReduce : 0.03, magReduce : 0.03 }, effect : [] };
itemList[152] = { id : 152, name : '근위대 예장', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 286, evasion : -0.05, phyReduce : 0.05, magReduce : 0.05 }, effect : [] };
itemList[153] = { id : 153, name : '중무장 무사의 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 403, evasion : -0.05, phyReduce : 0.07, magReduce : 0.07 }, effect : [] };
itemList[154] = { id : 154, name : '미완성 미스릴 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 546, evasion : -0.05, phyReduce : 0.09, magReduce : 0.09 }, effect : [] };
itemList[155] = { id : 155, name : '드워븐메이드 플레이트', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 715, evasion : -0.05, phyReduce : 0.11, magReduce : 0.11 }, effect : [] };
itemList[156] = { id : 156, name : '궁정 기사의 갑주', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 910, evasion : -0.05, phyReduce : 0.13, magReduce : 0.13 }, effect : [] };
itemList[157] = { id : 157, name : '미완성 하르콘 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_COMMON, stat : { maxHp : 1131, evasion : -0.05, phyReduce : 0.16, magReduce : 0.16 }, effect : [] };
itemList[158] = { id : 158, name : '경비대 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 57, evasion : -0.05, phyReduce : 0.011, magReduce : 0.011 }, effect : [] };
itemList[159] = { id : 159, name : '보철 판금 갑옷', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 114, evasion : -0.05, phyReduce : 0.022, magReduce : 0.022 }, effect : [] };
itemList[160] = { id : 160, name : '로리카 세크먼타타에', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 215, evasion : -0.05, phyReduce : 0.033, magReduce : 0.033 }, effect : [] };
itemList[161] = { id : 161, name : '트랜지셔널 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 315, evasion : -0.05, phyReduce : 0.055, magReduce : 0.055 }, effect : [] };
itemList[162] = { id : 162, name : '풀 플레이트 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 443, evasion : -0.05, phyReduce : 0.077, magReduce : 0.077 }, effect : [] };
itemList[163] = { id : 163, name : '실버 플레이트 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 601, evasion : -0.05, phyReduce : 0.099, magReduce : 0.099 }, effect : [] };
itemList[164] = { id : 164, name : '타이탄 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 787, evasion : -0.05, phyReduce : 0.121, magReduce : 0.121 }, effect : [] };
itemList[165] = { id : 165, name : '고리의 기사의 갑주', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 1001, evasion : -0.05, phyReduce : 0.143, magReduce : 0.143 }, effect : [] };
itemList[166] = { id : 166, name : '하르콘 플레이트 아머', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_ARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { maxHp : 1244, evasion : -0.05, phyReduce : 0.176, magReduce : 0.176 }, effect : [] };
itemList[167] = { id : 167, name : '삼각 방패', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 2, maxHp : 18 }, effect : [] };
itemList[168] = { id : 168, name : '버클러', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 4, maxHp : 35 }, effect : [] };
itemList[169] = { id : 169, name : '견고한 강철 방패', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 7, maxHp : 66 }, effect : [] };
itemList[170] = { id : 170, name : '카이트 실드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 10, maxHp : 97 }, effect : [] };
itemList[171] = { id : 171, name : '출정 기사의 방패', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 14, maxHp : 136 }, effect : [] };
itemList[172] = { id : 172, name : '드레이크 본 실드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 18, maxHp : 185 }, effect : [] };
itemList[173] = { id : 173, name : '티타늄 방패', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 23, maxHp : 242 }, effect : [] };
itemList[174] = { id : 174, name : '타워 실드', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 29, maxHp : 308 }, effect : [] };
itemList[175] = { id : 175, name : '하르콘 방패', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { dmgReduce : 36, maxHp : 383 }, effect : [] };
itemList[176] = { id : 176, name : '무명 신발', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 18 }, effect : [] };
itemList[177] = { id : 177, name : '가죽 장화', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 35 }, effect : [] };
itemList[178] = { id : 178, name : '신형 전투화', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 66 }, effect : [] };
itemList[179] = { id : 179, name : '고풍스러운 구두', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 97 }, effect : [] };
itemList[180] = { id : 180, name : '출정 기사의 장화', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 136 }, effect : [] };
itemList[181] = { id : 181, name : '장인의 가죽 신발', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 185 }, effect : [] };
itemList[182] = { id : 182, name : '요정의 장화', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 242 }, effect : [] };
itemList[183] = { id : 183, name : '윙 부츠', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 308 }, effect : [] };
itemList[184] = { id : 184, name : '하르콘 부츠', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { evasion : 0.05, maxHp : 383 }, effect : [] };
itemList[185] = { id : 185, name : '무명 장갑', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 18 }, effect : [] };
itemList[186] = { id : 186, name : '궁수의 수련 장갑', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 35 }, effect : [] };
itemList[187] = { id : 187, name : '3M장갑', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 66 }, effect : [] };
itemList[188] = { id : 188, name : '학자의 브레이슬릿', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 97 }, effect : [] };
itemList[189] = { id : 189, name : '출정 기사의 건틀릿', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 136 }, effect : [] };
itemList[190] = { id : 190, name : '글러브 오브 헤이스트', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 185 }, effect : [] };
itemList[191] = { id : 191, name : '수놓은 귀족의 장갑', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 242 }, effect : [] };
itemList[192] = { id : 192, name : '마력강화 강철 장갑', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 308 }, effect : [] };
itemList[193] = { id : 193, name : '하르콘 건틀릿', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { hit : 0.075, maxHp : 383 }, effect : [] };
itemList[194] = { id : 194, name : '무명 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 9, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 18 }, effect : [] };
itemList[195] = { id : 195, name : '빨간 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 8, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 35 }, effect : [] };
itemList[196] = { id : 196, name : '종자의 가죽 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 7, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 66 }, effect : [] };
itemList[197] = { id : 197, name : '흑곰가죽 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 6, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 97 }, effect : [] };
itemList[198] = { id : 198, name : '사막 전사의 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 5, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 136 }, effect : [] };
itemList[199] = { id : 199, name : '7색 비단망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 4, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 185 }, effect : [] };
itemList[200] = { id : 200, name : '엘프숲 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 3, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 242 }, effect : [] };
itemList[201] = { id : 201, name : '흑기사의 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 2, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 308 }, effect : [] };
itemList[202] = { id : 202, name : '고룡의 가죽 망토', nameType : cons.NAME_KOR_NO_END_CONS, type : cons.ITEM_TYPE_SUBARMOR, rank : 1, rarity : cons.ITEM_RARITY_UNCOMMON, stat : { spCharge : 2, maxHp : 383 }, effect : [] };
itemList[203] = { id : 203, name : '스탠다드 나인', type : cons.ITEM_TYPE_WEAPON, flavor : '- 아아, 이것은 표준이라는 것이다. 모든 능력치를 고르게 올려주지.<br>- 정말 대단해!', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 10, phyAtkMax : 14, magAtkMin : 10, magAtkMax : 14, phyReduce : 0.01, magReduce : 0.01, maxHp : 20, crit : 0.03, critDmg : 0.1, hit : 0.02, evasion : 0.02 }, 
effectDesc : '', effect : [] };
itemList[204] = { id : 204, name : '꿈의 사슬', type : cons.ITEM_TYPE_WEAPON, flavor : '', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 8, phyAtkMax : 16, magAtkMin : 8, magAtkMax : 16, crit : 0.02 }, 
effectDesc : '공격 성공 시 5% 확률로 적에게 [수면] 상태이상 부여, 피격 시 1% 확률로 자신에게 [수면] 상태이상 부여', 
effect : [{code : cons.EFFECT_TYPE_OPP_BUFF, active : cons.ACTIVE_TYPE_ATTACK, chance : 0.05, buffCode : 5, buffDur : 1}, 
          {code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_TAKE_HIT, chance : 0.01, buffCode : 5, buffDur : 1}] };
itemList[205] = { id : 205, name : '호박석 검', type : cons.ITEM_TYPE_WEAPON, flavor : '녹아내린 호박석이 검날을 따라 흘러내리는 의식용으로나 쓸 법한 검.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 4, phyAtkMax : 8, magAtkMin : 16, magAtkMax : 20, crit : 0.02 }, 
effectDesc : '마법 공격 성공 시 15% 확률로 적에게 2턴 간 [화상] 상태이상 부여', 
effect : [{code : cons.EFFECT_TYPE_OPP_BUFF, active : cons.ACTIVE_TYPE_ATTACK, chance : 0.15, buffCode : 1, buffDur : 2}] };
itemList[206] = { id : 206, name : '심플리스트 #9', type : cons.ITEM_TYPE_WEAPON, flavor : '단순함이 최고라고들 한다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 13, phyAtkMax : 14, magAtkMin : 13, magAtkMax : 14, crit : 0.03 }, 
effectDesc : '', effect : [] };
itemList[207] = { id : 207, name : '갱단의 비밀무기', type : cons.ITEM_TYPE_WEAPON, flavor : '어느 뒷골목 갱단이 중요한 일에 사용하는 검. 손잡이의 버튼을 누르면 검날에 갈라진 틈을 통해 독이 새어나온다. 잘못 휘두르면 자기가 독을 뒤집어 쓸 수 있다고 한다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 8, phyAtkMax : 10, magAtkMin : 8, magAtkMax : 10, crit : 0.04 }, 
effectDesc : '공격 성공 시 20% 확률로 적에게 1턴 간 [중독] 상태이상 부여, 피격 시 10% 확률로 자신에게 1턴 간 [중독] 상태이상 부여', 
effect : [{code : cons.EFFECT_TYPE_OPP_BUFF, active : cons.ACTIVE_TYPE_ATTACK, chance : 0.2, buffCode : 2, buffDur : 1}, 
          {code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_TAKE_HIT, chance : 0.1, buffCode : 2, buffDur : 1}] };
itemList[208] = { id : 208, name : '유리검', type : cons.ITEM_TYPE_WEAPON, flavor : '유리로 만들어진 검. 아주 예리하지만 금방 날이 깨져 버린다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 15, phyAtkMax : 21, magAtkMin : 15, magAtkMax : 21, crit : 0.02 }, 
effectDesc : '전투 시작 8턴 후 자신에게 [깨진 유리검] 디버프 부여<br><br>[깨진 유리검] : 물리/마법공격력 -15', 
effect : [{code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_TURN_START, chance : 1, buffCode : 10001, buffDur : null, chkTurn : 8, chkNot : [10001]}] };
itemList[209] = { id : 209, name : '수련용 허수아비의 팔', type : cons.ITEM_TYPE_WEAPON, flavor : '수련장에 떨어져 있던 허수아비의 팔이다. 인간에 대한 강한 원념이 느껴진다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 8, phyAtkMax : 12, magAtkMin : 10, magAtkMax : 18, crit : 0.02 }, 
effectDesc : '공격 성공 시 적에게 1턴 간 [허수아비의 원념] 디버프 부여<br><br>[허수아비의 원념] : 물리/마법저항 -2%', 
effect : [{code : cons.EFFECT_TYPE_OPP_BUFF, active : cons.ACTIVE_TYPE_ATTACK, chance : 1, buffCode : 10002, buffDur : 1}] };
itemList[210] = { id : 210, name : '호신용 화승총', type : cons.ITEM_TYPE_WEAPON, flavor : '동쪽 대륙의 우수한 기술력으로 만든 작은 화승총. 귀족들의 호신용 무기로 인기가 높다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 10, phyAtkMax : 18, magAtkMin : 8, magAtkMax : 12, crit : 0.02, hit : 0.03 }, 
effectDesc : '', effect : [] };
itemList[211] = { id : 211, name : '저주받은 검 2', type : cons.ITEM_TYPE_WEAPON, flavor : '전설의 검이 저주받은 모습. 도신에 기괴한 검은 무늬가 새겨져 있다. 이 검의 저주를 풀려면 무수한 작업을 요하지만 안타깝게도 이곳에선 그런 거 없다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 27, phyAtkMax : 33, magAtkMin : 27, magAtkMax : 33, crit : 0.02 }, 
effectDesc : '공격 성공 시 12% 확률로 자신에게 1턴 간 [기절] 상태이상을 부여하고 15의 고정 마법 피해를 입힘', 
effect : [{code : cons.EFFECT_TYPE_MULTIPLE, active : cons.ACTIVE_TYPE_ATTACK, chance : 0.12, target : [{code : cons.EFFECT_TYPE_SELF_BUFF, chance : 1, buffCode : 4, buffDur : 1}, {code : cons.EFFECT_TYPE_SELF_HIT, chance : 1, type : cons.DAMAGE_TYPE_MAGICAL_FIXED, value : 15}]}] };
itemList[212] = { id : 212, name : '고향의 별 - 아이우스타', type : cons.ITEM_TYPE_WEAPON, flavor : '부랑자이자 연금술사였던 니오비움의 검. 손잡이에 새겨진 연금술 시료를 사용하면 니오비움의 불꽃의 힘을 일으킬 수도 있다. 고향을 잃은 그리움을 따서 이름을 지었다.', rank : 9, rarity : cons.ITEM_RARITY_EPIC, stat : { phyAtkMin : 8, phyAtkMax : 12, magAtkMin : 12, magAtkMax : 24, crit : 0.03 }, 
effectDesc : '턴 시작 시 자신에게 [불길의 아이우스타] 버프가 없을 경우 SP 20을 소모하고 3턴 간 [불길의 아이우스타] 버프 부여<br><br>[불길의 아이우스타] : 공격 성공 시 적에게 16의 추가 마법 피해, 3% 확률로 적에게 1턴 간 [화상] 상태이상 부여 ', 
effect : [{code : cons.EFFECT_TYPE_MULTIPLE, active : cons.ACTIVE_TYPE_TURN_START, chance : 1, chkSp : 20, target : [{code : cons.EFFECT_TYPE_SELF_BUFF, chance : 1, buffCode : 10006, buffDur : 3}, {code : cons.EFFECT_TYPE_SELF_SP, chance : 1, value : -20}], chkNot : [10006]}] };
itemList[213] = { id : 213, name : '검은 정원의 가지', type : cons.ITEM_TYPE_WEAPON, flavor : '영계에 존재한다는 신의 정원을 가꾸기 위한 칼. 형태가 없는 것도 베어낼 수 있다. 과거 제3세계에 흘러들어온 영계의 정원사가 두고 간 것으로 추정된다.', rank : 9, rarity : cons.ITEM_RARITY_EPIC, stat : { phyAtkMin : 12, phyAtkMax : 24, magAtkMin : 8, magAtkMax : 12, spRegen : 2, crit : 0.05 }, 
effectDesc : '공격 성공 시 3% 확률로 적에게 3턴 간 [검은 정원의 가지] 디버프 부여<br><br>[검은 정원의 가지] : 물리/마법저항 0%로 고정', 
effect : [{code : cons.EFFECT_TYPE_OPP_BUFF, active : cons.ACTIVE_TYPE_ATTACK, chance : 1.03, buffCode : 10007, buffDur : 3}] };
itemList[214] = { id : 214, name : '천광곤 - 떡락의 시작', type : cons.ITEM_TYPE_WEAPON, flavor : '존버... 또 존버 하십시오...', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 13, phyAtkMax : 19, magAtkMin : 8, magAtkMax : 12, maxHp : 60, crit : 0.04, evasion : 0.02 }, 
effectDesc : '공격 시 5 고정 마법 피해, 2턴마다 턴 시작 시 자신에게 [가치 하락] 디버프 부여<br><br>[가치 하락] : 물리/마법공격력 -1%p', 
effect : [{code : cons.EFFECT_TYPE_ADD_HIT, active : cons.ACTIVE_TYPE_ATTACK, chance : 1, type : cons.DAMAGE_TYPE_MAGICAL_FIXED, value : 5},
          {code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_TURN_START, chance : 1, buffCode : 10003, buffDur : null, setCooldown : 1}] };
itemList[215] = { id : 215, name : '킬릭 - 공포의 아귀', type : cons.ITEM_TYPE_WEAPON, flavor : '검은색의 탁한 기운을 내뿜는 도검. 강력한 힘을 내지만 그 사용자는 대가를 감내해야 할 것이다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 14, phyAtkMax : 18, magAtkMin : 14, magAtkMax : 18, crit : 0.02 }, 
effectDesc : '전투 시작 시 자신에게 [샤에 물듦] 디버프 부여<br><br>[샤에 물듦] : 상대에게 피해를 줄 때마다 자신이 준 피해의 10%만큼 절대 피해를 입음 ', 
effect : [{code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_BATTLE_START, chance : 1, buffCode : 10004, buffDur : null}] };
itemList[216] = { id : 216, name : '바이로훈 - 기사단의 핏빛 장창', type : cons.ITEM_TYPE_WEAPON, flavor : '어딘가의 기사단이 사용했던 듯한 장창. 가벼운 재질로 어느 위치의 적이든 공격할 수 있을 듯하다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 11, phyAtkMax : 19, magAtkMin : 7, magAtkMax : 15, crit : 0.02 }, 
effectDesc : '물리 공격 성공 시 20% 확률로 저항 0으로 계산', 
effect : [{code : cons.EFFECT_TYPE_SELF_BUFF, active : cons.ACTIVE_TYPE_SKILL_WIN, chance : 0.2, buffCode : 10005, buffDur : 1, chkDmgType : cons.DAMAGE_TYPE_PHYSICAL}] };
itemList[217] = { id : 217, name : '바람의 두루마기', type : cons.ITEM_TYPE_ARMOR, flavor : '바람의 기운이 느껴지는 가벼운 복장. 물리 공격에 효과가 있을지는 의문이 든다..', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { magReduce : 0.025, maxHp : 34, spRegen : 1, evasion : 0.05 }, 
effectDesc : '', effect : [] };
itemList[218] = { id : 218, name : '광신도의 예복', type : cons.ITEM_TYPE_ARMOR, flavor : '그분의 말씀이 들리나?', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 28, spRegen : 1, evasion : 0.05 }, 
effectDesc : '<br><br>[광신] : 치명+5, 이 상태이상은 상성 패배시 사라진다. ', effect : [] };
itemList[219] = { id : 219, name : '디 클래식 #9', type : cons.ITEM_TYPE_ARMOR, flavor : '기본형의 고급 갑옷.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyReduce : 0.012, magReduce : 0.012, maxHp : 48, critDmg : 0.1 }, 
effectDesc : '', effect : [] };
itemList[220] = { id : 220, name : '누호에스 - 기사단의 경갑', type : cons.ITEM_TYPE_ARMOR, flavor : '어딘가의 기사단이 사용했던 듯한 갑옷. 가벼운 재질로 날렵하게 움직일 수 있다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyReduce : 0.01, magReduce : 0.01, maxHp : 48, critDmg : 0.1, hit : 0.02, evasion : 0.02 }, 
effectDesc : '', effect : [] };
itemList[221] = { id : 221, name : '호박석 갑옷', type : cons.ITEM_TYPE_ARMOR, flavor : '마력으로 굳힌 호박석을 덧댄 갑옷. 마법에는 취약하다는 모양이다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyReduce : 0.025, maxHp : 62, evasion : -0.05 }, 
effectDesc : '', effect : [] };
itemList[222] = { id : 222, name : '기암괴석', type : cons.ITEM_TYPE_ARMOR, flavor : '마치 갑옷처럼 생긴 오래된 암석. 이 무거운 것을 입을 생각을 하다니 제정신일까?', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 73, evasion : -0.05 }, 
effectDesc : '', effect : [] };
itemList[223] = { id : 223, name : '키릴 - 야수의 격노', type : cons.ITEM_TYPE_ARMOR, flavor : '다양한 야수의 가죽을 모아 만든 갑옷. 착용하면 점점 강렬한 힘이 느껴진다고 한다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyReduce : 0.013000000000000001, magReduce : 0.013000000000000001, maxHp : 37, spRegen : 1, evasion : 0.05 }, 
effectDesc : '<br><br>[야수의 격노] : 물리 최대 공격력 +1 (스택당) ', effect : [] };
itemList[224] = { id : 224, name : '평온의 의복', type : cons.ITEM_TYPE_ARMOR, flavor : '착용자를 평온하게 만드는 기이한 옷.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : -5, phyAtkMax : -5, magAtkMin : -5, magAtkMax : -5, phyReduce : 0.02, magReduce : 0.02, spRegen : 1, critDmg : -0.15, evasion : 0.09, dmgReduce : 4 }, 
effectDesc : '', effect : [] };
itemList[225] = { id : 225, name : '독뱀의 시선', type : cons.ITEM_TYPE_ARMOR, flavor : '남부 밀림에 서식하는 독뱀의 가죽을 겹대어 만든 갑옷.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyReduce : 0.013000000000000001, magReduce : 0.013000000000000001, maxHp : 52, critDmg : 0.1 }, 
effectDesc : '<br><br>[마비] - 회피절반감소. 공용 상태이상 ', effect : [] };
itemList[226] = { id : 226, name : '백은갑옷', type : cons.ITEM_TYPE_ARMOR, flavor : '백은으로 장식된 갑옷. 백은에는 그 자체로 마력을 막아 주는 힘이 있다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyReduce : 0.01, magReduce : 0.016, maxHp : 67, evasion : -0.05 }, 
effectDesc : '<br><br>[백은 수호] : 마법저항+5% ', effect : [] };
itemList[227] = { id : 227, name : '죽음인도자의 결의', type : cons.ITEM_TYPE_ARMOR, flavor : '강력한 죽음의 기사의 결의가 담긴 갑옷. 룬이 갑옷 곳곳에 새겨져 있고 강력한 한기가 느껴진다.', rank : 9, rarity : cons.ITEM_RARITY_EPIC, stat : { phyReduce : 0.015, magReduce : 0.015, maxHp : 73, spCharge : 2, evasion : -0.05 }, 
effectDesc : '<br><br>[춤추는 룬 무기] : 공격 시 효과 발동 처리를 한 번 더 한다. ', effect : [] };
itemList[228] = { id : 228, name : '세라이브 - 기사단의 방패', type : cons.ITEM_TYPE_SUBARMOR, flavor : '어딘가의 기사단이 사용했던 듯한 방패. 가벼운 재질로 공격을 흘려보내는 데 유용하다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, evasion : 0.03, dmgReduce : 2 }, 
effectDesc : '', effect : [] };
itemList[229] = { id : 229, name : '냄비 뚜껑', type : cons.ITEM_TYPE_SUBARMOR, flavor : '스테인리스로 만들어진 튼튼한 냄비 뚜껑. 상대의 전의를 상실시키기에도 좋다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, dmgReduce : 2 }, 
effectDesc : '', effect : [] };
itemList[230] = { id : 230, name : '호박석 방패', type : cons.ITEM_TYPE_SUBARMOR, flavor : '마력으로 굳힌 호박석을 덧댄 방패. 마법에는 취약하다는 모양이다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, dmgReduce : 3 }, 
effectDesc : '<br><br>[부서지는 호박석] : 마법저항-0.2% ', effect : [] };
itemList[231] = { id : 231, name : '스피드 부츠 #9', type : cons.ITEM_TYPE_SUBARMOR, flavor : 'undefined', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, evasion : 0.05 }, 
effectDesc : '<br><br>[스피드 업!] : 회피 +1% ', effect : [] };
itemList[232] = { id : 232, name : '공사용 장갑', type : cons.ITEM_TYPE_SUBARMOR, flavor : '공사 작업에 유용한 장갑. 부수는 일에 쓰기 좋다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, hit : 0.075, pierce : 0.03 }, 
effectDesc : '', effect : [] };
itemList[233] = { id : 233, name : '칼날 망토', type : cons.ITEM_TYPE_SUBARMOR, flavor : '칼날이 달린 망토.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 19, spCharge : 2 }, 
effectDesc : '', effect : [] };
itemList[234] = { id : 234, name : '피크닉용 돗자리', type : cons.ITEM_TYPE_SUBARMOR, flavor : '튼튼한 재질로 만든 돗자리. 망토처럼 두를 수 있지만 모양세는 좋지 않다.', rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { maxHp : 15, hpRegen : 3, spRegen : -1, spCharge : 2 }, 
effectDesc : '', effect : [] };
itemList[235] = { id : 235, name : '드렁큰 스텝', type : cons.ITEM_TYPE_SUBARMOR, flavor : '동양의 한 괴짜 권법가가 신었다는 부츠. 적의 공격을 흘리고 더욱 강력한 공격으로 받아칠 수 있도록 도와준다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { maxHp : 14, evasion : 0.07 }, 
effectDesc : '', effect : [] };
itemList[236] = { id : 236, name : '녹아내리는 손', type : cons.ITEM_TYPE_SUBARMOR, flavor : '엄청난 열로 둘러싸인 장갑. 잘못 사용했다가는..', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { maxHp : 21, crit : 0.05, hit : 0.075 }, 
effectDesc : '', effect : [] };
itemList[237] = { id : 237, name : '백호의 은혜', type : cons.ITEM_TYPE_SUBARMOR, flavor : '백호의 기운이 담긴 망토. 치유의 기운이 감돈다.', rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { maxHp : 21, spCharge : 2 }, 
effectDesc : '', effect : [] };
itemList[238] = { id : 238, name : '이글거리는 망토', type : cons.ITEM_TYPE_SUBARMOR, flavor : '화염의 흑마술사 바이레스의 망토. 꺼지지 않는 검붉은 불꽃으로 타오르고 있다.', rank : 9, rarity : cons.ITEM_RARITY_EPIC, stat : { maxHp : 25, spCharge : 3 }, 
effectDesc : '<br><br>[이글거리는 망토-지옥화염] : 매턴마다 15의 마법데미지를 입는다. ', effect : [] };


itemList[82] = { id : 0, name : '﻿레어 무기 9', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 9, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 10, phyAtkMax : 14, magAtkMin : 10, magAtkMax : 14, crit : 0.02 }, effect : [] }
itemList[83] = { id : 1, name : '레어 무기 8', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_RARE, stat : { phyAtkMin : 16, phyAtkMax : 20, magAtkMin : 16, magAtkMax : 20, crit : 0.02 }, effect : [] }
itemList[84] = { id : 0, name : '﻿유니크 무기 9', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 9, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 11, phyAtkMax : 15, magAtkMin : 11, magAtkMax : 15, crit : 0.03 }, effect : [] }
itemList[85] = { id : 1, name : '유니크 무기 8', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_UNIQUE, stat : { phyAtkMin : 19, phyAtkMax : 23, magAtkMin : 19, magAtkMax : 23, crit : 0.03 }, effect : [] }
itemList[86] = { id : 0, name : '﻿에픽 무기 9', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 9, rarity : cons.ITEM_RARITY_EPIC, stat : { phyAtkMin : 12, phyAtkMax : 16, magAtkMin : 12, magAtkMax : 16, crit : 0.03 }, effect : [] }
itemList[87] = { id : 1, name : '에픽 무기 8', nameType : cons.NAME_KOR_END_CONS, type : cons.ITEM_TYPE_WEAPON, rank : 8, rarity : cons.ITEM_RARITY_EPIC, stat : { phyAtkMin : 22, phyAtkMax : 26, magAtkMin : 22, magAtkMax : 26, crit : 0.03 }, effect : [] }

itemList.forEach(function(tgt) {
  tgt.base = JSON.parse(JSON.stringify(tgt.stat));
})
